name: Hello World on Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: self-hosted  # This tells GitHub Actions to use your self-hosted runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello, World! Running on a self-hosted Linux runner!"
